# SPDX-License-Identifier: GPL-3.0-or-later
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
  jobs:
    pre_build:
      # Generate API reference with Doxygen into Sphinx static path
      - doxygen docs/Doxyfile

sphinx:
  configuration: docs/conf.py
  builder: html

python:
  install:
    - requirements: docs/requirements.txt

formats: []
